### ISSUE TITLE
Trying to Install this but No Framework File to Import - Swift 2

### ISSUE THREAD

**Issue by lenichols** [athiercelin/ATSketchKit#22]
Perhaps my XCode newbe is showing today but i see the ATSketchKit directory with all the swift files in it. I was wondering can someone tell me how to compile these files into a framework for use into my current project. Can't seem to get it figured out.

I need to add this to my project but don't know how to create a framework file... Why isn't this included in the github pkg? Just curious.

![screen shot 2016-03-02 at 1 32 43 pm](https://cloud.githubusercontent.com/assets/5247113/13476168/61f728f4-e07b-11e5-8b3b-d104279b50fa.png)

**Comment by e7711bbear** [comment]
I've added a build release of the framework in the releases section of github.

**Comment by lenichols** [comment]
Thanks a bunch for this...
