### ISSUE TITLE
Error running demo

### ISSUE THREAD

**Issue by terenzeyuen** [athiercelin/ATSketchKit#25]
Hi, just downloaded but having a lot of errors compiling...am I missing something? Please kindly advise..

<img width="925" alt="screen shot 2016-09-09 at 19 05 12" src="https://cloud.githubusercontent.com/assets/2553680/18397602/d8bf96ca-76c0-11e6-97ee-32957dbc102b.png">

**Comment by e7711bbear** [comment]
Hi,

That's normal, I'm in the process of converting the source to swift 3.
I've done a lot of the work during the summer, but with each new Xcode came new changes to be made and I need to finish.
I'll get back to it as soon as I can, but I have a lot of work these days.

Sorry for the inconvenience.
