### ISSUE TITLE
ATSketchkit not working in Xcode 8

### ISSUE THREAD

**Issue by Pamposgsk** [athiercelin/ATSketchKit#26]
I get fatal error:use of unimplemented initializer 'init(layer:)' for class ATSketchkit.ATSketchTopLayer

**Comment by e7711bbear** [comment]
Please recheck if it still is the case with the latest PR

**Comment by Pamposgsk** [comment]
works perfect!!! Thanks a lot

**Comment by e7711bbear** [comment]
Thanks @Tornquist :) and feel free to PR ;)
