### ISSUE TITLE
Recognizing shapes

### ISSUE THREAD

**Issue by hussnainwaris** [athiercelin/ATSketchKit#29]
Hello
In the swift 3 update, you have commented out the template part and gesture recognizer delegate method are not implemented. Can you please share the code for gesture recognizing and overriding the recognized path drawing. I saw the youtube video where you showed that output.

**Comment by e7711bbear** [comment]
Let me look into this tomorrow.

**Comment by ghost** [comment]
In swift 3 with the template part commented back in the compiler goes into an endless build. 

To fix it:
let points : Array<CGPoint> = // ... the template array
newRectTemplate.points = points

**Comment by e7711bbear** [comment]
Sorry I haven't had time to look into this. Do you mind raising a PR?
