### ISSUE TITLE
Apple Mach-O Linker (id) Error

### ISSUE THREAD

**Issue by prasanth223344** [athiercelin/ATSketchKit#31]
I get the Macho-O error when I try to archive the app, everything else works fine though, no matter what I try I couldn't resolve that, Kindly help, additionally I get this warning which I believe the cause for the error.

Thanks,

ld: warning: ignoring file /Users/dev/Documents/test/ATSketchKit.framework/ATSketchKit, file was built for arm64 which is not the architecture being linked (armv7): /Users/dev/Documents/test/ATSketchKit.framework/ATSketchKit

**Comment by e7711bbear** [comment]
Try linking the whole project so that it gets built with your app on the same architecture.

**Comment by prasanth223344** [comment]
ah thanks for your quick reply, yes, now I did importing my files into your demo and it worked just fine,

**Comment by prasanth223344** [comment]
ah thanks for your quick reply, yes, now I did importing my files into your demo and it worked just fine,
